SELECT  
    CASE WHEN GRADES.GRADE < 8 THEN 'NULL' ELSE STUDENTS.NAME END AS Name,
    GRADES.GRADE AS Grade,
    STUDENTS.MARKS AS Mark
FROM STUDENTS
INNER JOIN GRADES
ON STUDENTS.MARKS >= GRADES.MIN_MARK
AND STUDENTS.MARKS <= GRADES.MAX_MARK
ORDER BY 
    GRADES.GRADE DESC,
    CASE 
        WHEN GRADES.GRADE < 8 THEN STUDENTS.MARKS
        ELSE STUDENTS.NAME
END ASC;